In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from pandas import DataFrame, Series
import matplotlib.pyplot as plt

#engine 解決utf8的問題
data = pd.read_csv("新竹_2019.csv", engine='python')
data

,測站,日期,測項,00,01,02,03,04,05,06,...,14,15,16,17,18,19,20,21,22,23
0,--------------------,--------------------,--------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,...,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------
1,新竹,2019/01/01 00:00:00,AMB_TEMP,17.5,17.4,17.3,17.1,16.8,16.9,16.8,...,20,19.5,18.7,18.1,17.9,17.6,17.6,17.5,17.7,17.5
2,新竹,2019/01/01 00:00:00,CH4,1.79,1.78,1.8,1.8,1.8,1.8,1.8,...,1.81,1.81,1.81,1.8,1.8,1.81,1.81,1.8,1.8,1.79
3,新竹,2019/01/01 00:00:00,CO,0.19,0.21,0.22,0.22,0.21,0.21,0.23,...,0.29,0.3,0.31,0.31,0.31,0.3,0.29,0.27,0.26,0.24
4,新竹,2019/01/01 00:00:00,NMHC,0.04,0.04,0.04,0.04,0.04,0.04,0.04,...,0.06,0.06,0.07,0.07,0.07,0.06,0.05,0.04,0.04,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6476,新竹,2019/12/31 00:00:00,THC,1.81,1.79,1.82,1.84,1.84,1.85,1.85,...,1.89,1.9,1.89,1.9,1.88,1.84,1.81,1.81,1.81,1.8
6477,新竹,2019/12/31 00:00:00,WD_HR,42,41,40,41,38,42,41,...,34,40,40,49,48,51,57,50,49,53
6478,新竹,2019/12/31 00:00:00,WIND_DIREC,35,42,36,47,41,35,35,...,26,44,46,35,50,47,64,40,55,52
6479,新竹,2019/12/31 00:00:00,WIND_SPEED,3.7,3.5,3.4,3.7,4.6,5,4.8,...,3.6,5,3.9,4.7,5.1,4.4,4.1,4.4,3.7,4.6
6480,新竹,2019/12/31 00:00:00,WS_HR,2.6,2.7,2.9,3.6,3.4,3.5,3.5,...,3.5,3.6,3.4,3.6,3.5,3.7,3.5,3.1,3.2,3.6

In [2]:
#print(data.columns)
#刪除欄位標頭的空白
data.columns = data.columns.str.strip()
data.columns

Index(['測站', '日期', '測項', '00', '01', '02', '03', '04', '05', '06', '07', '08',
       '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23'],
      dtype='object')

In [3]:
#清除数據左右的空格
newName = data['測站'].str.strip();
data['測站'] = newName;
newName = data['測項'].str.strip();
data['測項'] = newName;
newName = data['日期'].str.strip();
data['日期'] = newName;
newName = data['00'].str.strip();
data['00'] = newName;
newName = data['01'].str.strip();
data['01'] = newName;
newName = data['02'].str.strip();
data['02'] = newName;
newName = data['03'].str.strip();
data['03'] = newName;
newName = data['04'].str.strip();
data['04'] = newName;
newName = data['05'].str.strip();
data['05'] = newName;
newName = data['06'].str.strip();
data['06'] = newName;
newName = data['07'].str.strip();
data['07'] = newName;
newName = data['08'].str.strip();
data['08'] = newName;
newName = data['09'].str.strip();
data['09'] = newName;
newName = data['10'].str.strip();
data['10'] = newName;
newName = data['11'].str.strip();
data['11'] = newName;
newName = data['12'].str.strip();
data['12'] = newName;
newName = data['13'].str.strip();
data['13'] = newName;
newName = data['14'].str.strip();
data['14'] = newName;
newName = data['15'].str.strip();
data['15'] = newName;
newName = data['16'].str.strip();
data['16'] = newName;
newName = data['17'].str.strip();
data['17'] = newName;
newName = data['18'].str.strip();
data['18'] = newName;
newName = data['19'].str.strip();
data['19'] = newName;
newName = data['20'].str.strip();
data['20'] = newName;
newName = data['21'].str.strip();
data['21'] = newName;
newName = data['22'].str.strip();
data['22'] = newName;
newName = data['23'].str.strip();
data['23'] = newName;
#data['日期'].unique()
#data['14'].isin(['#']).sum(axis=0)

In [4]:
#取出10.11.12月資料
start_date = "2019/09/30 00:00:00 "
end_date = "2019/12/31 00:00:00 "

after_start_date = data["日期"] >= start_date
before_end_date = data["日期"] <= end_date
between_two_dates = after_start_date & before_end_date
filtered_data = data.loc[between_two_dates]
#print(filtered_data)

In [5]:
#將index作重置
filtered_data.reset_index(drop=True, inplace=True)
filtered_data

,測站,日期,測項,00,01,02,03,04,05,06,...,14,15,16,17,18,19,20,21,22,23
0,新竹,2019/10/01 00:00:00,AMB_TEMP,24.7,25.1,25.4,25.5,25.3,25.1,24.6,...,32.4,31.9,30.4,29.1,28.7,28.3,28,27.4,27,26.5
1,新竹,2019/10/01 00:00:00,CH4,1.66,1.66,1.7,1.71,1.72,1.71,1.75,...,1.69,1.72,1.74,1.74,1.78,1.82,1.82,1.83,1.93,1.96
2,新竹,2019/10/01 00:00:00,CO,0.05,0.13,0.15,0.17,0.16,0.16,0.22,...,0.27,0.32,0.36,0.39,0.49,0.57,0.58,0.6,0.69,0.49
3,新竹,2019/10/01 00:00:00,NMHC,0,0,0,0.02,0.02,0.01,0.03,...,0.07,0.1,0.08,0.08,0.13,0.21,0.22,0.21,0.22,0.17
4,新竹,2019/10/01 00:00:00,NO,0,0.3,0.3,0.3,0.3,0.3,1.2,...,1.6,1.1,0.8,0.6,0.6,0.7,0.6,2,5.1,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,新竹,2019/12/31 00:00:00,THC,1.81,1.79,1.82,1.84,1.84,1.85,1.85,...,1.89,1.9,1.89,1.9,1.88,1.84,1.81,1.81,1.81,1.8
1652,新竹,2019/12/31 00:00:00,WD_HR,42,41,40,41,38,42,41,...,34,40,40,49,48,51,57,50,49,53
1653,新竹,2019/12/31 00:00:00,WIND_DIREC,35,42,36,47,41,35,35,...,26,44,46,35,50,47,64,40,55,52
1654,新竹,2019/12/31 00:00:00,WIND_SPEED,3.7,3.5,3.4,3.7,4.6,5,4.8,...,3.6,5,3.9,4.7,5.1,4.4,4.1,4.4,3.7,4.6
1655,新竹,2019/12/31 00:00:00,WS_HR,2.6,2.7,2.9,3.6,3.4,3.5,3.5,...,3.5,3.6,3.4,3.6,3.5,3.7,3.5,3.1,3.2,3.6

In [6]:
new_data = filtered_data
new_data = new_data.drop(['測站', '日期','測項'], axis=1)
#row和column互轉
new_data = new_data.T
for i in range(len(new_data.columns)):
    new_data[i] = new_data[i].str.replace('A', '#')
    new_data[i] = new_data[i].str.replace('NA', '#')
    new_data[i] = new_data[i].str.replace('x', '#')
    new_data[i] = new_data[i].str.replace('*', '#')
for i in range(len(new_data.columns)):
    for j in range(len(new_data[i])):
        if ('#') in new_data[i][j]:
            new_data[i][j] = np.nan
#print(new_data[1250])
for i in range(len(new_data.columns)):
     new_data[i] = new_data[i].astype('float64')
#使用插值法，缺失值由前一個值和後一個值得平均数；interpolate（）假設函數是線性
new_data = new_data.interpolate()
#print(new_data[1250])

In [7]:
new_data_2 =  filtered_data
#先拿掉測站，無助於分析
new_data_2 = new_data_2.drop(['測站'], axis=1)
new_data_2 = new_data_2.drop(['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'], axis=1)
#進行轉置
new_data = new_data.T
#兩個資料集合併
dataset = pd.concat([new_data_2, new_data], axis=1)
dataset = dataset.T
#將資料切割成訓練集(10.11月)以及測試集(12月)
X = dataset.iloc[:,0:1098]
y = dataset.iloc[:,1098:1656]
y

,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,...,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655
日期,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,2019/12/01 00:00:00,...,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00,2019/12/31 00:00:00
測項,AMB_TEMP,CH4,CO,NMHC,NO,NO2,NOx,O3,PM10,PM2.5,...,PM10,PM2.5,RAINFALL,RH,SO2,THC,WD_HR,WIND_DIREC,WIND_SPEED,WS_HR
00,20.5,1.86,0.28,0.08,0.6,13.7,14.3,21.5,41,18,...,10,7,0,84,1.2,1.81,42,35,3.7,2.6
01,20.1,1.91,0.29,0.1,0.3,11.9,12.3,18.4,41,18,...,5,6,0,84,0.5,1.79,41,42,3.5,2.7
02,19.9,1.89,0.24,0.09,0.3,11.1,11.5,19.2,39,18,...,12,5,0,84,0.5,1.82,40,36,3.4,2.9
03,19.8,1.87,0.2,0.09,0.6,8.6,9.2,20.9,37,16,...,14,7,0,84,0.5,1.84,41,47,3.7,3.6
04,20.1,1.96,0.23,0.1,0.3,8.6,9,18.9,41,18,...,12,9,0,83,0.5,1.84,38,41,4.6,3.4
05,20.1,1.86,0.22,0.08,0.96,9.28,10.32,20.1,39,18,...,18,10,0,83,0.5,1.85,42,35,5,3.5
06,19.9,1.86,0.3,0.11,1.62,9.96,11.64,14.4,38,15,...,19,11,0,82,0.5,1.85,41,35,4.8,3.5
07,19.7,1.9,0.46,0.15,2.28,10.64,12.96,9,38,26,...,21,10,0,81,0.5,1.88,45,46,4.5,3.6
08,20.8,1.81,0.39,0.12,2.94,11.32,14.28,16.6,41,21,...,5,8,0,83,0.5,1.89,39,44,4.7,3.7
09,22.9,1.76,0.32,0.09,3.6,12,15.6,32.1,34,23,...,15,8,0,83,0.5,1.88,45,52,5.3,3.6
10,24.7,1.8,0.41,0.12,2.5,11.7,14.1,44.9,33,19,...,14,7,0,80,0.5,1.86,44,41,5,4.1
11,25,1.77,0.32,0.09,1.6,9.7,11.2,52.6,49,23,...,15,10,0,75,1.1,1.89,41,34,5.5,3.7
12,24.2,1.73,0.25,0.06,1.1,7.2,8.2,56,42,21,...,19,11,0,74,0.5,1.89,37,34,5.7,3.9
13,23.7,1.72,0.23,0.05,0.8,6,6.8,60.7,38,17,...,21,16,0,72,1.1,1.9,39,35,4.5,3.8
14,23,1.73,0.23,0.04,0.3,6,6.5,61.4,37,20,...,22,14,0,73,1,1.89,34,26,3.6,3.5
15,22.6,1.74,0.26,0.05,0.5,6.1,6.6,61.3,33,21,...,27,18,0,74,0.5,1.9,40,44,5,3.6
16,22.3,1.75,0.28,0.07,0.3,7.8,7.9,55.9,34,17,...,32,20,0,76,0.5,1.89,40,46,3.9,3.4
17,22,1.78,0.36,0.12,0.3,12,12.3,47,36,22,...,26,17,0,74,1,1.9,49,35,4.7,3.6
18,21.7,1.77,0.37,0.12,0.3,13.1,13.4,45.2,38,19,...,24,18,0,73,1.2,1.88,48,50,5.1,3.5
19,21.3,1.75,0.32,0.08,0.3,12.4,12.6,43.7,33,19,...,22,12,0,72,1.4,1.84,51,47,4.4,3.7
20,21,1.77,0.29,0.09,0.3,12.7,13,38.2,36,18,...,24,13,0,73,1.4,1.81,57,64,4.1,3.5
21,21,1.81,0.32,0.12,0.3,15.7,16.1,28.1,36,15,...,27,10,0,72,1.7,1.81,50,40,4.4,3.1
22,21,1.79,0.27,0.09,0.4,14.35,14.8,24.6,33,15,...,28,12,0,72,1.6,1.81,49,55,3.7,3.2
23,20.7,1.79,0.29,0.09,0.5,13,13.5,22,32,12,...,30,11,0,73,1.4,1.8,53,52,4.6,3.6

In [8]:
#製作時序資料
date_rng = pd.date_range(start='10/01/2019', end='12/01/2019', freq='H')
date_rng_2 = pd.date_range(start='12/01/2019', end='01/01/2020', freq='H')
df = pd.DataFrame(date_rng, columns=['date'])
df_2 = pd.DataFrame(date_rng_2, columns=['date'])
df_2['datetime'] = pd.to_datetime(df_2['date'])
df['datetime'] = pd.to_datetime(df['date']) 
#df = df.set_index('datetime')
df.drop(['date'], axis=1, inplace=True)
df_2.drop(['date'], axis=1, inplace=True)
df = df.iloc[0:1464]
df_2 = df_2.iloc[0:744]
df_2

               datetime
0   2019-12-01 00:00:00
1   2019-12-01 01:00:00
2   2019-12-01 02:00:00
3   2019-12-01 03:00:00
4   2019-12-01 04:00:00
..                  ...
739 2019-12-31 19:00:00
740 2019-12-31 20:00:00
741 2019-12-31 21:00:00
742 2019-12-31 22:00:00
743 2019-12-31 23:00:00

[744 rows x 1 columns]

In [9]:
X = X.T
X = X.drop(['日期'], axis=1)
y = y.T
y = y.drop(['日期'], axis=1)
y

,測項,00,01,02,03,04,05,06,07,08,...,14,15,16,17,18,19,20,21,22,23
1098,AMB_TEMP,20.5,20.1,19.9,19.8,20.1,20.1,19.9,19.7,20.8,...,23,22.6,22.3,22,21.7,21.3,21,21,21,20.7
1099,CH4,1.86,1.91,1.89,1.87,1.96,1.86,1.86,1.9,1.81,...,1.73,1.74,1.75,1.78,1.77,1.75,1.77,1.81,1.79,1.79
1100,CO,0.28,0.29,0.24,0.2,0.23,0.22,0.3,0.46,0.39,...,0.23,0.26,0.28,0.36,0.37,0.32,0.29,0.32,0.27,0.29
1101,NMHC,0.08,0.1,0.09,0.09,0.1,0.08,0.11,0.15,0.12,...,0.04,0.05,0.07,0.12,0.12,0.08,0.09,0.12,0.09,0.09
1102,NO,0.6,0.3,0.3,0.6,0.3,0.96,1.62,2.28,2.94,...,0.3,0.5,0.3,0.3,0.3,0.3,0.3,0.3,0.4,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,THC,1.81,1.79,1.82,1.84,1.84,1.85,1.85,1.88,1.89,...,1.89,1.9,1.89,1.9,1.88,1.84,1.81,1.81,1.81,1.8
1652,WD_HR,42,41,40,41,38,42,41,45,39,...,34,40,40,49,48,51,57,50,49,53
1653,WIND_DIREC,35,42,36,47,41,35,35,46,44,...,26,44,46,35,50,47,64,40,55,52
1654,WIND_SPEED,3.7,3.5,3.4,3.7,4.6,5,4.8,4.5,4.7,...,3.6,5,3.9,4.7,5.1,4.4,4.1,4.4,3.7,4.6
1655,WS_HR,2.6,2.7,2.9,3.6,3.4,3.5,3.5,3.6,3.7,...,3.5,3.6,3.4,3.6,3.5,3.7,3.5,3.1,3.2,3.6

In [10]:
#將訓練集每18行合併，轉換成維度為(18,61*24)的DataFrame(每個屬性都有61天*24小時共1464筆資料)
temp = pd.DataFrame({'測項':['AMB_TEMP','CH4','CO','NMHC','NO','NO2','NOx','O3','PM10','PM2.5','RAINFALL','RH','SO2','THC','WD_HR','WIND_DIREC','WIND_SPEED','WS_HR'],
                        })
a = pd.DataFrame()
new_X = pd.DataFrame()
for i in range(0,1097,18):
    a = X.iloc[i:i+18]
    a.reset_index(drop=True, inplace=True)
    a = a.drop(['測項'], axis=1)
    new_X = pd.concat([new_X, a], axis=1)
new_X = new_X.T
new_X.reset_index(drop=True, inplace=True)
#欄(column)代表逐時數據資料
new_X = pd.concat([df, new_X], axis=1)
new_X = new_X.T
new_X = new_X.rename(index={0:'AMB_TEMP', 1:'CH4', 2:'CO', 3:'NMHC', 4:'NO', 5:'NO2', 6:'NOx', 7:'O3', 8:'PM10', 9:'PM2.5', 10:'RAINFALL', 11:'RH', 12:'SO2', 13:'THC', 14:'WD_HR', 15:'WIND_DIREC', 16:'WIND_SPEED', 17:'WS_HR'})
new_X

#處理測試集
y.reset_index(drop=True, inplace=True)
b = pd.DataFrame()
new_y = pd.DataFrame()
for i in range(0,558,18):
    b = y.iloc[i:i+18]
    b.reset_index(drop=True, inplace=True)
    b = b.drop(['測項'], axis=1)
    new_y = pd.concat([new_y, b], axis=1)
new_y = new_y.T
new_y.reset_index(drop=True, inplace=True)
#欄(column)代表逐時數據資料
new_y = pd.concat([df_2, new_y], axis=1)
new_y = new_y.T
new_y = new_y.rename(index={0:'AMB_TEMP', 1:'CH4', 2:'CO', 3:'NMHC', 4:'NO', 5:'NO2', 6:'NOx', 7:'O3', 8:'PM10', 9:'PM2.5', 10:'RAINFALL', 11:'RH', 12:'SO2', 13:'THC', 14:'WD_HR', 15:'WIND_DIREC', 16:'WIND_SPEED', 17:'WS_HR'})
new_y

,0,1,2,3,4,5,6,7,8,9,...,734,735,736,737,738,739,740,741,742,743
datetime,2019-12-01 00:00:00,2019-12-01 01:00:00,2019-12-01 02:00:00,2019-12-01 03:00:00,2019-12-01 04:00:00,2019-12-01 05:00:00,2019-12-01 06:00:00,2019-12-01 07:00:00,2019-12-01 08:00:00,2019-12-01 09:00:00,...,2019-12-31 14:00:00,2019-12-31 15:00:00,2019-12-31 16:00:00,2019-12-31 17:00:00,2019-12-31 18:00:00,2019-12-31 19:00:00,2019-12-31 20:00:00,2019-12-31 21:00:00,2019-12-31 22:00:00,2019-12-31 23:00:00
AMB_TEMP,20.5,20.1,19.9,19.8,20.1,20.1,19.9,19.7,20.8,22.9,...,16.3,15.9,15.4,15.3,15.3,15.1,15,15,15,15.2
CH4,1.86,1.91,1.89,1.87,1.96,1.86,1.86,1.9,1.81,1.76,...,1.79,1.79,1.78,1.78,1.77,1.75,1.74,1.74,1.74,1.74
CO,0.28,0.29,0.24,0.2,0.23,0.22,0.3,0.46,0.39,0.32,...,0.4,0.39,0.4,0.43,0.43,0.36,0.31,0.3,0.29,0.29
NMHC,0.08,0.1,0.09,0.09,0.1,0.08,0.11,0.15,0.12,0.09,...,0.1,0.11,0.11,0.12,0.11,0.09,0.07,0.07,0.07,0.06
NO,0.6,0.3,0.3,0.6,0.3,0.96,1.62,2.28,2.94,3.6,...,1.6,1.4,1.1,1.1,0.8,0.8,0.3,0.8,0.6,0.3
NO2,13.7,11.9,11.1,8.6,8.6,9.28,9.96,10.64,11.32,12,...,9.8,10.8,11.3,12.8,12.7,10.8,8.8,8.6,7.8,6.9
NOx,14.3,12.3,11.5,9.2,9,10.32,11.64,12.96,14.28,15.6,...,11.3,12.2,12.4,14,13.5,11.5,9.2,9.3,8.4,7.3
O3,21.5,18.4,19.2,20.9,18.9,20.1,14.4,9,16.6,32.1,...,33.4,31.4,31.4,30.6,31.2,33.3,34.1,34.1,34.1,33.7
PM10,41,41,39,37,41,39,38,38,41,34,...,22,27,32,26,24,22,24,27,28,30
PM2.5,18,18,18,16,18,18,15,26,21,23,...,14,18,20,17,18,12,13,10,12,11
RAINFALL,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RH,86,88,89,89,88,88,87,84,78,68,...,73,74,76,74,73,72,73,72,72,73
SO2,2.1,1.8,2,1.6,1.6,1.6,1.7,1.8,2,1.8,...,1,0.5,0.5,1,1.2,1.4,1.4,1.7,1.6,1.4
THC,1.94,2.01,1.98,1.96,2.06,1.94,1.97,2.05,1.93,1.85,...,1.89,1.9,1.89,1.9,1.88,1.84,1.81,1.81,1.81,1.8
WD_HR,171,181,169,179,187,187,156,54,49,69,...,34,40,40,49,48,51,57,50,49,53
WIND_DIREC,176,181,174,177,189,167,92,35,67,134,...,26,44,46,35,50,47,64,40,55,52
WIND_SPEED,0.8,0.7,0.9,0.8,0.7,0.8,0.6,0.8,1,0.9,...,3.6,5,3.9,4.7,5.1,4.4,4.1,4.4,3.7,4.6
WS_HR,0.9,0.5,0.9,0.8,0.5,0.6,0.4,0.7,0.9,0.6,...,3.5,3.6,3.4,3.6,3.5,3.7,3.5,3.1,3.2,3.6

In [11]:
#將未來第一個小時當預測目標(第一個 PM2.5)
temp = new_X.T['PM2.5']
temp
temp_2 = pd.DataFrame()
temp_3 = pd.DataFrame()
X_train = temp.iloc[0:6]
y_train = temp.iloc[0:7]
for i in range(1,1464):
    if(i == 1458):
         break
    else:
        temp_2 = temp.iloc[i:i+6]
        temp_2.reset_index(drop=True, inplace=True)
        X_train = pd.concat([X_train, temp_2], axis=1)
        
        temp_3 = temp.iloc[i:i+7]
        temp_3.reset_index(drop=True, inplace=True)
        y_train = pd.concat([y_train, temp_3], axis=1)
X_train = X_train.T
y_train = y_train.T
y_train = y_train.drop([0,1,2,3,4,5], axis = 1)
y_train

#處理測試集
temp = new_y.T['PM2.5']
temp_2 = pd.DataFrame()
temp_3 = pd.DataFrame()
X_test = temp.iloc[0:6]
y_test = temp.iloc[0:7]
for i in range(1,744):
    if(i == 738):
         break
    else:
        temp_2 = temp.iloc[i:i+6]
        temp_2.reset_index(drop=True, inplace=True)
        X_test = pd.concat([X_test, temp_2], axis=1)
        
        temp_3 = temp.iloc[i:i+7]
        temp_3.reset_index(drop=True, inplace=True)
        y_test = pd.concat([y_test, temp_3], axis=1)
X_test = X_test.T
y_test = y_test.T
y_test = y_test.drop([0,1,2,3,4,5], axis = 1)
y_test

        6
PM2.5  15
PM2.5  26
PM2.5  21
PM2.5  23
PM2.5  19
...    ..
PM2.5  12
PM2.5  13
PM2.5  10
PM2.5  12
PM2.5  11

[738 rows x 1 columns]

In [12]:
#將未來第一個小時當預測目標(第二個:所有18種屬性)
X_all_train = []
y_all_train = []
for i in range(1,len(new_X.T.columns)):
    temp = new_X.T[new_X.T.columns[i]]
    temp_2 = pd.DataFrame()
    temp_3 = pd.DataFrame()
    X_train_2 = temp.iloc[0:6]
    y_train_2 = temp.iloc[0:7]
    for i in range(1,1464):
        if(i == 1458):
            break
        else:
            temp_2 = temp.iloc[i:i+6]
            temp_2.reset_index(drop=True, inplace=True)
            X_train_2 = pd.concat([X_train_2, temp_2], axis=1)

            temp_3 = temp.iloc[i:i+7]
            temp_3.reset_index(drop=True, inplace=True)
            y_train_2 = pd.concat([y_train_2, temp_3], axis=1)
    X_train_2 = X_train_2.T
    y_train_2 = y_train_2.T
    y_train_2 = y_train_2.drop([0,1,2,3,4,5], axis = 1)
    if (i==2):
        X_all_train = X_train_2
        y_all_train = y_train_2
    else:
        X_all_train.append(X_train_2)
        y_all_train.append(y_train_2)


A = pd.DataFrame()
X_all_new_train = pd.DataFrame()
X_all_new_train = X_all_train[0]
X_all_new_train.reset_index(drop=True, inplace=True)
for i in range(1,len(X_all_train)):
    A = X_all_train[i]
    A.reset_index(drop=True, inplace=True)
    X_all_new_train = pd.concat([X_all_new_train, A], axis=1)

In [13]:
X_all_new_train[2]

,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
0,25.4,1.7,0.15,0,0.3,1.3,1.7,21.9,29,6,0,85,1.4,1.7,291,276,2,1.8
1,25.5,1.71,0.17,0.02,0.3,1.8,2.1,21.5,29,9,0,84,1.5,1.73,286,289,2.5,2.2
2,25.3,1.72,0.16,0.02,0.3,2.1,2.4,18.8,27,10,0,85,1.5,1.74,268,250,1.8,1.8
3,25.1,1.71,0.16,0.01,0.3,2.3,2.7,17.5,19,7,0,86,1.6,1.72,277,262,2.4,1.9
4,24.6,1.75,0.22,0.03,1.2,6.1,7.3,11.8,23,4,0,88,1.8,1.78,247,239,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,25.1,1.82,0.4,0.12,1.7,22.9,24.6,52.1,51,35,0,54,4.6,1.94,271,273,1.7,1.6
1454,23.6,1.83,0.41,0.12,1,20.1,21.1,48.1,41,17,0,65,3.9,1.95,257,244,1.3,1.5
1455,22.4,1.83,0.42,0.11,0.5,13.7,14.2,51.8,38,20,0,75,2.3,1.94,246,167,0.8,1.3
1456,22.1,1.87,0.56,0.17,0.6,24.5,25.1,37,42,22,0,78,3.3,2.04,213,178,0.9,0.6
1457,21.7,2,0.69,0.23,1.6,33.4,34.9,21,56,34,0,79,3.5,2.23,165,162,1.2,0.9

In [14]:
#將未來第一個小時當預測目標
A = pd.DataFrame()
y_all_new_train = pd.DataFrame()
y_all_new_train = y_all_train[0]
y_all_new_train.reset_index(drop=True, inplace=True)
for i in range(1,len(y_all_train)):
    A = y_all_train[i]
    A.reset_index(drop=True, inplace=True)
    y_all_new_train = pd.concat([y_all_new_train, A], axis=1)
y_all_new_train

,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
0,24.6,1.75,0.22,0.03,1.2,6.1,7.3,11.8,23,4,0,88,1.8,1.78,247,239,2,2
1,24.6,1.76,0.42,0.08,5.3,9.9,15.2,8.2,13,6,0,90,2,1.84,203,183,1.7,1
2,25.1,1.73,0.36,0.08,5.6,7.4,12.9,10.4,10,7,0,85,1.9,1.81,193,187,2.3,1.5
3,26.8,1.73,0.29,0.08,4.8,6,10.8,13.2,13,6,0,75,1.9,1.81,200,196,2.8,2
4,28.5,1.72,0.27,0.08,4.6,6.1,10.7,16.6,15,4,0,67,1.8,1.8,197,194,2.6,1.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,21.7,2,0.69,0.23,1.6,33.4,34.9,21,56,34,0,79,3.5,2.23,165,162,1.2,0.9
1454,21.2,1.97,0.71,0.23,2.6,31.8,34.4,15.4,56,36,0,81,3,2.2,198,225,0.8,0.5
1455,21,1.85,0.48,0.15,1,22.3,23.2,23,51,32,0,83,3.1,2,162,170,0.9,0.6
1456,20.9,1.9,0.5,0.15,1.1,22.7,23.7,16.4,41,27,0,84,2.4,2.05,167,115,0.9,0.6
1457,20.8,1.84,0.34,0.1,0.7,16.5,17.2,20.8,47,22,0,85,2.2,1.94,168,179,1,1

In [15]:
#處理測試集
X_all_test = []
y_all_test = []
for i in range(1,len(new_y.T.columns)):
    temp = new_y.T[new_y.T.columns[i]]
    temp_2 = pd.DataFrame()
    temp_3 = pd.DataFrame()
    X_test_2 = temp.iloc[0:6]
    y_test_2 = temp.iloc[0:7]
    for i in range(1,744):
        if(i == 738):
            break
        else:
            temp_2 = temp.iloc[i:i+6]
            temp_2.reset_index(drop=True, inplace=True)
            X_test_2 = pd.concat([X_test_2, temp_2], axis=1)

            temp_3 = temp.iloc[i:i+7]
            temp_3.reset_index(drop=True, inplace=True)
            y_test_2 = pd.concat([y_test_2, temp_3], axis=1)
    X_test_2 = X_test_2.T
    y_test_2 = y_test_2.T
    y_test_2 = y_test_2.drop([0,1,2,3,4,5], axis = 1)
    if (i==2):
        X_all_test = X_test_2
        y_all_test = y_test_2
    else:
        X_all_test.append(X_test_2)
        y_all_test.append(y_test_2)


A = pd.DataFrame()
X_all_new_test = pd.DataFrame()
X_all_new_test = X_all_test[0]
X_all_new_test.reset_index(drop=True, inplace=True)
for i in range(1,len(X_all_test)):
    A = X_all_test[i]
    A.reset_index(drop=True, inplace=True)
    X_all_new_test = pd.concat([X_all_new_test, A], axis=1)
X_all_new_test

A = pd.DataFrame()
y_all_new_test = pd.DataFrame()
y_all_new_test = y_all_test[0]
y_all_new_test.reset_index(drop=True, inplace=True)
for i in range(1,len(y_all_test)):
    A = y_all_test[i]
    A.reset_index(drop=True, inplace=True)
    y_all_new_test = pd.concat([y_all_new_test, A], axis=1)
y_all_new_test

,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
0,19.9,1.86,0.3,0.11,1.62,9.96,11.64,14.4,38,15,0,87,1.7,1.97,156,92,0.6,0.4
1,19.7,1.9,0.46,0.15,2.28,10.64,12.96,9,38,26,0,84,1.8,2.05,54,35,0.8,0.7
2,20.8,1.81,0.39,0.12,2.94,11.32,14.28,16.6,41,21,0,78,2,1.93,49,67,1,0.9
3,22.9,1.76,0.32,0.09,3.6,12,15.6,32.1,34,23,0,68,1.8,1.85,69,134,0.9,0.6
4,24.7,1.8,0.41,0.12,2.5,11.7,14.1,44.9,33,19,0,61,1.7,1.92,287,284,1,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,15.1,1.75,0.36,0.09,0.8,10.8,11.5,33.3,22,12,0,72,1.4,1.84,51,47,4.4,3.7
734,15,1.74,0.31,0.07,0.3,8.8,9.2,34.1,24,13,0,73,1.4,1.81,57,64,4.1,3.5
735,15,1.74,0.3,0.07,0.8,8.6,9.3,34.1,27,10,0,72,1.7,1.81,50,40,4.4,3.1
736,15,1.74,0.29,0.07,0.6,7.8,8.4,34.1,28,12,0,72,1.6,1.81,49,55,3.7,3.2
737,15.2,1.74,0.29,0.06,0.3,6.9,7.3,33.7,30,11,0,73,1.4,1.8,53,52,4.6,3.6

In [16]:
#將未來第六個小時當預測目標
temp = new_X.T['PM2.5']
temp
temp_2 = pd.DataFrame()
temp_3 = pd.DataFrame()
next_X_train = temp.iloc[0:6]
next_y_train = temp.iloc[0:11]
for i in range(1,1464):
    if(i == 1453):
         break
    else:
        temp_2 = temp.iloc[i:i+6]
        temp_2.reset_index(drop=True, inplace=True)
        next_X_train = pd.concat([next_X_train, temp_2], axis=1)
        
        temp_3 = temp.iloc[i:i+11]
        temp_3.reset_index(drop=True, inplace=True)
        next_y_train = pd.concat([next_y_train, temp_3], axis=1)
next_X_train = next_X_train.T
next_y_train = next_y_train.T
next_y_train = next_y_train.drop([0,1,2,3,4,5,6,7,8,9], axis = 1)
next_X_train

        0   1   2   3   4   5
PM2.5   2   4   6   9  10   7
PM2.5   4   6   9  10   7   4
PM2.5   6   9  10   7   4   6
PM2.5   9  10   7   4   6   7
PM2.5  10   7   4   6   7   6
...    ..  ..  ..  ..  ..  ..
PM2.5   5   5   8  14  18  15
PM2.5   5   8  14  18  15  16
PM2.5   8  14  18  15  16  35
PM2.5  14  18  15  16  35  17
PM2.5  18  15  16  35  17  20

[1453 rows x 6 columns]

In [17]:
#處理測試集
#將未來第一個小時當預測目標
temp = new_y.T['PM2.5']
temp_2 = pd.DataFrame()
temp_3 = pd.DataFrame()
next_X_test = temp.iloc[0:6]
next_y_test = temp.iloc[0:11]
for i in range(1,744):
    if(i == 733):
         break
    else:
        temp_2 = temp.iloc[i:i+6]
        temp_2.reset_index(drop=True, inplace=True)
        next_X_test = pd.concat([next_X_test, temp_2], axis=1)
        
        temp_3 = temp.iloc[i:i+11]
        temp_3.reset_index(drop=True, inplace=True)
        next_y_test = pd.concat([next_y_test, temp_3], axis=1)
next_X_test= next_X_test.T
next_y_test = next_y_test.T
next_y_test = next_y_test.drop([0,1,2,3,4,5,6,7,8,9], axis = 1)
next_X_test

        0   1   2   3   4   5
PM2.5  18  18  18  16  18  18
PM2.5  18  18  16  18  18  15
PM2.5  18  16  18  18  15  26
PM2.5  16  18  18  15  26  21
PM2.5  18  18  15  26  21  23
...    ..  ..  ..  ..  ..  ..
PM2.5   8   8   7  10  11  16
PM2.5   8   7  10  11  16  14
PM2.5   7  10  11  16  14  18
PM2.5  10  11  16  14  18  20
PM2.5  11  16  14  18  20  17

[733 rows x 6 columns]

In [18]:
next_X_all_train = []
next_y_all_train = []
for i in range(1,len(new_X.T.columns)): 
    temp = new_X.T[new_X.T.columns[i]]
    temp_2 = pd.DataFrame()
    temp_3 = pd.DataFrame()
    next_X_train_2 = temp.iloc[0:6]
    next_y_train_2 = temp.iloc[0:11]
    for i in range(1,1464):
        if(i == 1453):
             break
        else:
            temp_2 = temp.iloc[i:i+6]
            temp_2.reset_index(drop=True, inplace=True)
            next_X_train_2 = pd.concat([next_X_train_2, temp_2], axis=1)

            temp_3 = temp.iloc[i:i+11]
            temp_3.reset_index(drop=True, inplace=True)
            next_y_train_2 = pd.concat([next_y_train_2, temp_3], axis=1)
    next_X_train_2 = next_X_train_2.T
    next_y_train_2 = next_y_train_2.T
    next_y_train_2 = next_y_train_2.drop([0,1,2,3,4,5,6,7,8,9], axis = 1)
    if (i==2):
        next_X_all_train = next_X_train_2
        next_y_all_train = next_y_train_2
    else:
        next_X_all_train.append(next_X_train_2)
        next_y_all_train.append(next_y_train_2)

In [19]:
A = pd.DataFrame()
next_X_all_new_train = pd.DataFrame()
next_X_all_new_train = next_X_all_train[0]
next_X_all_new_train.reset_index(drop=True, inplace=True)
for i in range(1,len(next_X_all_train)):
    A = next_X_all_train[i]
    A.reset_index(drop=True, inplace=True)
    next_X_all_new_train = pd.concat([next_X_all_new_train, A], axis=1)
next_X_all_new_train

,0,1,2,3,4,5,0,1,2,3,...,2,3,4,5,0,1,2,3,4,5
0,24.7,25.1,25.4,25.5,25.3,25.1,1.66,1.66,1.7,1.71,...,2,2.5,1.8,2.4,0.9,1.1,1.8,2.2,1.8,1.9
1,25.1,25.4,25.5,25.3,25.1,24.6,1.66,1.7,1.71,1.72,...,2.5,1.8,2.4,2,1.1,1.8,2.2,1.8,1.9,2
2,25.4,25.5,25.3,25.1,24.6,24.6,1.7,1.71,1.72,1.71,...,1.8,2.4,2,1.7,1.8,2.2,1.8,1.9,2,1
3,25.5,25.3,25.1,24.6,24.6,25.1,1.71,1.72,1.71,1.75,...,2.4,2,1.7,2.3,2.2,1.8,1.9,2,1,1.5
4,25.3,25.1,24.6,24.6,25.1,26.8,1.72,1.71,1.75,1.76,...,2,1.7,2.3,2.8,1.8,1.9,2,1,1.5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1448,19.3,21.6,23.7,24.9,25.1,25.1,1.81,1.78,1.77,1.79,...,1.4,2,2.3,2.3,1.1,0.8,0.6,1.2,1.6,1.7
1449,21.6,23.7,24.9,25.1,25.1,25.2,1.78,1.77,1.79,1.79,...,2,2.3,2.3,2.1,0.8,0.6,1.2,1.6,1.7,1.5
1450,23.7,24.9,25.1,25.1,25.2,25.1,1.77,1.79,1.79,1.76,...,2.3,2.3,2.1,1.7,0.6,1.2,1.6,1.7,1.5,1.6
1451,24.9,25.1,25.1,25.2,25.1,23.6,1.79,1.79,1.76,1.77,...,2.3,2.1,1.7,1.3,1.2,1.6,1.7,1.5,1.6,1.5
1452,25.1,25.1,25.2,25.1,23.6,22.4,1.79,1.76,1.77,1.82,...,2.1,1.7,1.3,0.8,1.6,1.7,1.5,1.6,1.5,1.3

In [20]:
A = pd.DataFrame()
next_y_all_new_train = pd.DataFrame()
next_y_all_new_train = next_y_all_train[0]
next_y_all_new_train.reset_index(drop=True, inplace=True)
for i in range(1,len(next_y_all_train)):
    A = next_y_all_train[i]
    A.reset_index(drop=True, inplace=True)
    next_y_all_new_train = pd.concat([next_y_all_new_train, A], axis=1)
next_y_all_new_train

,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
0,28.5,1.72,0.27,0.08,4.6,6.1,10.7,16.6,15,4,0,67,1.8,1.8,197,194,2.6,1.7
1,30.1,1.7,0.28,0.07,3.7,5.7,9.4,23.8,21,2,0,59,2.2,1.77,196,196,3.4,2.1
2,31.2,1.69,0.26,0.07,2.6,5.6,8.2,23.1,11,3,0,53,2,1.76,196,219,2.5,1.6
3,32.2,1.7,0.25,0.07,2.6,5.9,8.5,27.7,43,4,0,51,2.4,1.77,214,244,3.5,1.7
4,32.4,1.69,0.27,0.07,1.6,5.9,7.4,41,17,3,0,51,2,1.76,241,244,3.3,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1448,22.1,1.87,0.56,0.17,0.6,24.5,25.1,37,42,22,0,78,3.3,2.04,213,178,0.9,0.6
1449,21.7,2,0.69,0.23,1.6,33.4,34.9,21,56,34,0,79,3.5,2.23,165,162,1.2,0.9
1450,21.2,1.97,0.71,0.23,2.6,31.8,34.4,15.4,56,36,0,81,3,2.2,198,225,0.8,0.5
1451,21,1.85,0.48,0.15,1,22.3,23.2,23,51,32,0,83,3.1,2,162,170,0.9,0.6
1452,20.9,1.9,0.5,0.15,1.1,22.7,23.7,16.4,41,27,0,84,2.4,2.05,167,115,0.9,0.6

In [21]:
#處理測試集
next_X_all_test = []
next_y_all_test = []
for i in range(1,len(new_y.T.columns)): 
    temp = new_y.T[new_y.T.columns[i]]
    temp_2 = pd.DataFrame()
    temp_3 = pd.DataFrame()
    next_X_test_2 = temp.iloc[0:6]
    next_y_test_2 = temp.iloc[0:11]
    for i in range(1,744):
        if(i == 733):
             break
        else:
            temp_2 = temp.iloc[i:i+6]
            temp_2.reset_index(drop=True, inplace=True)
            next_X_test_2 = pd.concat([next_X_test_2, temp_2], axis=1)

            temp_3 = temp.iloc[i:i+11]
            temp_3.reset_index(drop=True, inplace=True)
            next_y_test_2 = pd.concat([next_y_test_2, temp_3], axis=1)
    next_X_test_2 = next_X_test_2.T
    next_y_test_2 = next_y_test_2.T
    next_y_test_2 = next_y_test_2.drop([0,1,2,3,4,5,6,7,8,9], axis = 1)
    if (i==2):
        next_X_all_test = next_X_test_2
        next_y_all_test = next_y_test_2
    else:
        next_X_all_test.append(next_X_test_2)
        next_y_all_test.append(next_y_test_2)

In [22]:
A = pd.DataFrame()
next_X_all_new_test = pd.DataFrame()
next_X_all_new_test = next_X_all_test[0]
next_X_all_new_test.reset_index(drop=True, inplace=True)
for i in range(1,len(next_X_all_test)):
    A = next_X_all_test[i]
    A.reset_index(drop=True, inplace=True)
    next_X_all_new_test = pd.concat([next_X_all_new_test, A], axis=1)
next_X_all_new_test

,0,1,2,3,4,5,0,1,2,3,...,2,3,4,5,0,1,2,3,4,5
0,20.5,20.1,19.9,19.8,20.1,20.1,1.86,1.91,1.89,1.87,...,0.9,0.8,0.7,0.8,0.9,0.5,0.9,0.8,0.5,0.6
1,20.1,19.9,19.8,20.1,20.1,19.9,1.91,1.89,1.87,1.96,...,0.8,0.7,0.8,0.6,0.5,0.9,0.8,0.5,0.6,0.4
2,19.9,19.8,20.1,20.1,19.9,19.7,1.89,1.87,1.96,1.86,...,0.7,0.8,0.6,0.8,0.9,0.8,0.5,0.6,0.4,0.7
3,19.8,20.1,20.1,19.9,19.7,20.8,1.87,1.96,1.86,1.86,...,0.8,0.6,0.8,1,0.8,0.5,0.6,0.4,0.7,0.9
4,20.1,20.1,19.9,19.7,20.8,22.9,1.96,1.86,1.86,1.9,...,0.6,0.8,1,0.9,0.5,0.6,0.4,0.7,0.9,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,16.4,16.1,16.2,16.8,16.9,17.1,1.8,1.8,1.78,1.78,...,5,5.5,5.7,4.5,3.7,3.6,4.1,3.7,3.9,3.8
729,16.1,16.2,16.8,16.9,17.1,16.3,1.8,1.78,1.78,1.79,...,5.5,5.7,4.5,3.6,3.6,4.1,3.7,3.9,3.8,3.5
730,16.2,16.8,16.9,17.1,16.3,15.9,1.78,1.78,1.79,1.79,...,5.7,4.5,3.6,5,4.1,3.7,3.9,3.8,3.5,3.6
731,16.8,16.9,17.1,16.3,15.9,15.4,1.78,1.79,1.79,1.79,...,4.5,3.6,5,3.9,3.7,3.9,3.8,3.5,3.6,3.4
732,16.9,17.1,16.3,15.9,15.4,15.3,1.79,1.79,1.79,1.79,...,3.6,5,3.9,4.7,3.9,3.8,3.5,3.6,3.4,3.6

In [23]:
A = pd.DataFrame()
next_y_all_new_test = pd.DataFrame()
next_y_all_new_test = next_y_all_test[0]
next_y_all_new_test.reset_index(drop=True, inplace=True)
for i in range(1,len(next_y_all_test)):
    A = next_y_all_test[i]
    A.reset_index(drop=True, inplace=True)
    next_y_all_new_test = pd.concat([next_y_all_new_test, A], axis=1)
next_y_all_new_test

,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
0,24.7,1.8,0.41,0.12,2.5,11.7,14.1,44.9,33,19,0,61,1.7,1.92,287,284,1,0.5
1,25,1.77,0.32,0.09,1.6,9.7,11.2,52.6,49,23,0,66,2.2,1.86,302,310,1.7,1.6
2,24.2,1.73,0.25,0.06,1.1,7.2,8.2,56,42,21,0,71,2.1,1.79,301,297,2.2,1.5
3,23.7,1.72,0.23,0.05,0.8,6,6.8,60.7,38,17,0,72,2.1,1.77,298,284,1.9,1.8
4,23,1.73,0.23,0.04,0.3,6,6.5,61.4,37,20,0,75,1.8,1.77,305,51,1.2,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,15.3,1.77,0.43,0.11,0.8,12.7,13.5,31.2,24,18,0,73,1.2,1.88,48,50,5.1,3.5
729,15.1,1.75,0.36,0.09,0.8,10.8,11.5,33.3,22,12,0,72,1.4,1.84,51,47,4.4,3.7
730,15,1.74,0.31,0.07,0.3,8.8,9.2,34.1,24,13,0,73,1.4,1.81,57,64,4.1,3.5
731,15,1.74,0.3,0.07,0.8,8.6,9.3,34.1,27,10,0,72,1.7,1.81,50,40,4.4,3.1
732,15,1.74,0.29,0.07,0.6,7.8,8.4,34.1,28,12,0,72,1.6,1.81,49,55,3.7,3.2

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.metrics import mean_absolute_error
from sklearn import ensemble, preprocessing, metrics
from sklearn.ensemble import RandomForestClassifier

reg = LinearRegression().fit(X_train,y_train)
y_pred = reg.predict(X_test)
MAE = metrics.mean_absolute_error(y_test, y_pred)

reg_2 = LinearRegression().fit(next_X_train,next_y_train)
y_pred_2 = reg_2.predict(next_X_test)
MAE_2 = metrics.mean_absolute_error(next_y_test, y_pred_2)
#訓練model
y_train = y_train.astype('int')
X_train = X_train.astype('int')
y_test = y_test.astype('int')
X_test = X_test.astype('int')
Random_forest = RandomForestClassifier(n_estimators = 200)
model = Random_forest.fit(X_train,y_train)
# Predictions
pred = model.predict(X_test)
MAE_3 = metrics.mean_absolute_error(y_test, pred)

next_y_train = next_y_train.astype('int')
next_X_train = next_X_train.astype('int')
next_y_test = next_y_test.astype('int')
next_X_test = next_X_test.astype('int')
Random_forest = ensemble.RandomForestClassifier(n_estimators = 200)
model_2 = Random_forest.fit(next_X_train,next_y_train)
# Predictions
pred_2 = model_2.predict(next_X_test)
MAE_4 = metrics.mean_absolute_error(next_y_test, pred_2)

#預測將未來第一個小時當預測目標
#PM2.5
print(MAE)
#預測將未來第六個小時當預測目標
#PM2.5
print(MAE_2)
#預測將未來第一個小時當預測目標
#PM2.5
print(MAE_3)
#預測將未來第六個小時當預測目標
#PM2.5
print(MAE_4)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

2.613339309443992
4.570520791503907
3.4390243902439024
5.829467939972715

In [25]:
X_all_new_train = X_all_new_train.astype('float')
X_all_new_train = X_all_new_train.interpolate()
y_all_new_train = y_all_new_train.astype('float')
y_all_new_train = y_all_new_train.interpolate()
reg_3 = LinearRegression().fit(X_all_new_train,y_all_new_train)
y_pred_3 = reg_3.predict(X_all_new_test)
MAE_5 = metrics.mean_absolute_error(y_all_new_test, y_pred_3)
#預測將未來第一個小時當預測目標
#18個屬性
print(MAE_5)

next_X_all_new_train = next_X_all_new_train.astype('float')
next_X_all_new_train = next_X_all_new_train.interpolate()
next_y_all_new_train = next_y_all_new_train.astype('float')
next_y_all_new_train = next_y_all_new_train.interpolate()
reg_4 = LinearRegression().fit(next_X_all_new_train,next_y_all_new_train)
y_pred_4 = reg_4.predict(next_X_all_new_test)
MAE_6 = metrics.mean_absolute_error(next_y_all_new_test, y_pred_4)
#預測將未來第六個小時當預測目標
#18個屬性
print(MAE_6)

Random_forest = ensemble.RandomForestClassifier(n_estimators = 200)
model_3 = Random_forest.fit(X_all_new_train,y_all_new_train.astype('int'))
# Predictions
pred_3 = model_3.predict(X_all_new_test)
MAE_7 = metrics.mean_absolute_error(y_all_new_test, pred_3)
#預測將未來第一個小時當預測目標
#18個屬性
print(MAE_7)

Random_forest = ensemble.RandomForestClassifier(n_estimators = 200)
model_4 = Random_forest.fit(next_X_all_new_train,next_y_all_new_train.astype('int'))
# Predictions
pred_4 = model_4.predict(next_X_all_new_test)
MAE_8 = metrics.mean_absolute_error(next_y_all_new_test, pred_4)
#預測將未來第六個小時當預測目標
#18個屬性
print(MAE_8)

5.030148821132336
9.44052020284445
6.638024314965371
8.018149790308726